[project]
name = "learn-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt==4.0.1",
    "fastapi>=0.128.6",
    "passlib[bcrypt]>=1.7.4",
    "sqlalchemy>=2.0.46",
    "uvicorn[standard]>=0.40.0",
]
